import { EntityManager } from './entity-manager';

export class EntityChanges {

	// All properties should be read only after being generated by the EntityManager
	// Some of them point straight back to the base data, do not change.

	deletedTypes: string[] = [];
	deletedEntities: any;

	addedTypes: string[] = [];
	addedEntities: any;

	modifiedTypes: string[] = [];
	modifiedEntities: any;

	constructor(public entityManager: EntityManager) { };

}
